classDiagram
  class axios {
    +version: 1.7.7
  }
  axios --> form-data
  axios --> proxy-from-env
  axios --> follow-redirects
  class form-data {
    +version: 4.0.0
  }
  class proxy-from-env {
    +version: 1.1.0
  }
  class follow-redirects {
    +version: 1.15.9
  }
